### ISSUE TITLE
Don't start a project in the DEV mode with play-tests 8.18

### ISSUE THREAD

**Issue by yuriuss** [codeborne/play-tests#7]
Hi All!
I'm using Play 1.5.x
Created an application just like: play new app1, then added all necessary dependencies.
Trying to run: $ play run
And I see an error:
```
~ play! 1.5.x-localbuild, https://www.playframework.com
~
~ using java version "1.8.0_191"
Listening for transport dt_socket at address: 8000
03:31:21,128 INFO  ~ Starting /home/user1/temp/app1
:: loading settings :: url = jar:file:/home/user1/play-1.5.x/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
03:31:21,412 INFO  ~ Module tests is available (/home/user1/temp/app1/modules/tests-8.18)
03:31:21,472 FATAL ~ Failed to start
java.lang.NoSuchMethodError: play.Play.runingInTestMode()Z
	at play.test.coverage.ActionCoveragePlugin.<init>(ActionCoveragePlugin.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at play.plugins.PluginCollection.loadPlugins(PluginCollection.java:168)
	at play.Play.init(Play.java:320)
	at play.server.Server.main(Server.java:162)
```

:(
What's wrong?

**Comment by yuriuss** [comment]
I resolved the problem. In the latest versions 1.5.2 and 1.5.1 are called the method as "ru**n**ingInTestMode" and in version 1.5.0 the method has name as "play.Play.ru**nn**ingInTestMode". I checked that in the "play-tests" module the reference was always to method "play.Play.ru**n**ingInTestMode". Apparently, the developers of this module have not tested with Play >1.5.0.

**Comment by asolntsev** [comment]
That's right, we haven't used this module for a while (because we migrated to RePlay framework).
I can update play-tests so that it works with Play 1.5. Will release a new version in few days.

**Comment by asolntsev** [comment]
@yuriuss Hi! Sorry for the delay.
Just in case, I released two versions:
* https://repo.codeborne.com/play-tests/tests-8.19.zip - only renamed `runingInTestMode` -> `runinngInTestMode`
* https://repo.codeborne.com/play-tests/tests-9.0.zip - upgrade to selenide:5.1.0, Gradle 4.10.3 and other dependencies
